;;; sapporo-night-theme.el --- A bright dark theme, inspired by Tokyo Night Storm and Nord -*- lexical-binding: t; -*-

;; Copyright (C) 2025

;; Author: SoraTenshi
;; Version: 0.1.0
;; URL: https://github.com/yourname/sapporo-night-theme

;;; Commentary:
;; This file defines the Sapporo Night theme, a bright dark theme with cool muted purple-blue tones.
;; Inspired by the Sapporo Snow Festival at night - cool, muted, snowy aesthetic.
;; Version 0.1.0 - Better contrast while maintaining cool muted palette

;;; Code:

(deftheme sapporo-night-rebuilt
  "A bright dark theme with cool muted purple-blue tones, like the Sapporo Snow Festival at night.")

(let ((class '((class color) (min-colors 89)))
      (bg "#2a2947")
      (bg-bright "#51518B")
      (bg-darker "#202037")
      (fg "#a0b7eb")
      (fg-alt "#95a8d8")
      (comment "#545d8a")     ; Slightly brighter for contrast, still cool
      (keyword "#ab8bf7")     ; Original cool purple
      (function "#9ab1fa")    ; Original cool light blue
      (string "#b0d4ff")      ; Original very light cool blue
      (variable "#95a8d8")    ; Muted, less cyan
      (constant "#a9c7ff")    ; Original light cool blue
      (builtin "#94b5f0")     ; Original cool blue
      (type "#8ea1ff")        ; Original light blue
      (line-hl "#33325d")
      (cursor "#bb9af7")
      (error "#c678dd")       ; ORIGINAL cool purple
      (warning "#9dc8f8")
      (info "#87a3d4")
      (success "#56d8f4")     ; Original cool cyan
      (border "#404070")
      (subtle "#6572a8")      ; Brighter for readability
      (faded "#4a5073"))      ; Original

  (custom-theme-set-faces
   'sapporo-night-rebuilt

   ;; Base faces
   `(default ((,class (:background ,bg :foreground ,fg))))
   `(cursor ((,class (:background ,cursor))))
   `(region ((,class (:background ,line-hl :foreground ,fg))))
   `(highlight ((,class (:background ,line-hl :foreground ,bg))))
   `(hl-line ((,class (:background nil
                                   :box (:line-width -1 :color ,line-hl)))))
   `(fringe ((,class (:background ,bg :foreground ,subtle))))
   `(vertical-border ((,class (:foreground ,border))))
   `(window-divider ((,class (:foreground ,border))))
   `(window-divider-first-pixel ((,class (:foreground ,border))))
   `(window-divider-last-pixel ((,class (:foreground ,border))))
   `(file-name-shadow ((,class (:foreground ,faded))))
   `(shadow ((,class (:foreground ,faded))))
   `(link ((,class (:foreground ,builtin :underline t))))
   `(link-visited ((,class (:foreground ,builtin :underline t))))

   ;; Font lock faces (syntax highlighting)
   `(font-lock-builtin-face ((,class (:inherit nil :foreground ,builtin))))
   `(font-lock-comment-face ((,class (:inherit nil :foreground ,comment :slant italic))))
   `(font-lock-comment-delimiter-face ((,class (:inherit nil :foreground ,comment :slant italic))))
   `(font-lock-constant-face ((,class (:inherit nil :foreground ,constant))))
   `(font-lock-function-name-face ((,class (:inherit nil :foreground ,function :slant italic))))
   `(font-lock-keyword-face ((,class (:inherit nil :foreground ,keyword :slant italic))))
   `(font-lock-string-face ((,class (:inherit nil :foreground ,string))))
   `(font-lock-type-face ((,class (:inherit nil :foreground ,type))))
   `(font-lock-variable-name-face ((,class (:inherit nil :foreground ,variable))))
   `(font-lock-warning-face ((,class (:inherit nil :foreground ,warning))))
   `(font-lock-doc-face ((,class (:inherit nil :foreground ,comment :slant italic))))
   `(font-lock-preprocessor-face ((,class (:inherit nil :foreground ,builtin))))
   `(font-lock-negation-char-face ((,class (:inherit nil :foreground ,error))))
   `(font-lock-regexp-grouping-backslash ((,class (:inherit nil :foreground ,keyword))))
   `(font-lock-regexp-grouping-construct ((,class (:inherit nil :foreground ,constant))))

   ;; Minibuffer and echo area
   `(minibuffer-prompt ((,class (:foreground ,keyword))))
   `(echo-area-message ((,class (:foreground ,fg))))

   ;; Mode line
   `(mode-line ((,class (:background ,line-hl :foreground ,fg :box nil))))
   `(mode-line-inactive ((,class (:background ,bg :foreground ,subtle :box nil))))
   `(mode-line-buffer-id ((,class (:foreground ,keyword))))

   ;; Line numbers
   `(line-number ((,class (:background ,bg :foreground ,subtle))))
   `(line-number-current-line ((,class (:background ,line-hl :foreground ,fg))))

   ;; Parentheses matching
   `(show-paren-match ((,class (:background ,line-hl :foreground ,fg))))
   `(show-paren-mismatch ((,class (:background ,error :foreground ,bg))))

   ;; Search and match
   `(isearch ((,class (:background ,warning :foreground ,bg))))
   `(lazy-highlight ((,class (:background ,line-hl :foreground ,fg))))
   `(match ((,class (:background ,info :foreground ,bg))))

   ;; Error faces
   `(error ((,class (:foreground ,error))))
   `(warning ((,class (:foreground ,warning))))
   `(success ((,class (:foreground ,success))))

   `(fill-column-indicator ((,class (:foreground ,faded :height 1.2))))

   ;; Whitespace mode
   `(whitespace-space ((,class (:foreground ,faded))))
   `(whitespace-tab ((,class (:foreground ,faded :background ,bg))))
   `(whitespace-newline ((,class (:foreground ,faded))))
   `(whitespace-trailing ((,class (:background ,error :foreground ,bg))))
   `(whitespace-line ((,class (:background nil :foreground nil))))
   `(whitespace-space-before-tab ((,class (:background ,warning :foreground ,bg))))
   `(whitespace-indentation ((,class (:background ,warning :foreground ,bg))))
   `(whitespace-empty ((,class (:background ,warning))))
   `(whitespace-space-after-tab ((,class (:background ,warning :foreground ,bg))))
   `(whitespace-missing-newline-at-eof ((,class (:background ,error :foreground ,bg))))
   `(whitespace-big-indent ((,class (:background ,warning :foreground ,bg))))
   `(whitespace-hspace ((,class (:foreground ,faded :background ,bg))))
   `(whitespace-indentation ((,class (:background ,warning :foreground ,bg))))

   ;; Vertico
   `(vertico-current ((,class (:background ,line-hl :foreground ,fg))))
   `(vertico-group-title ((,class (:foreground ,keyword))))
   `(vertico-group-separator ((,class (:foreground ,border))))
   `(vertico-multiline ((,class (:foreground ,comment))))

   ;; Orderless
   `(orderless-match-face-0 ((,class (:foreground ,keyword :weight bold))))
   `(orderless-match-face-1 ((,class (:foreground ,warning :weight bold))))
   `(orderless-match-face-2 ((,class (:foreground ,info :weight bold))))
   `(orderless-match-face-3 ((,class (:foreground ,success :weight bold))))
   `(orderless-match-face-4 ((,class (:foreground ,error :weight bold))))
   `(orderless-match-face-5 ((,class (:foreground ,keyword :weight bold))))

   ;; Marginalia
   `(marginalia-archive ((,class (:foreground ,info))))
   `(marginalia-char ((,class (:foreground ,constant))))
   `(marginalia-date ((,class (:foreground ,builtin))))
   `(marginalia-documentation ((,class (:foreground ,comment :slant italic))))
   `(marginalia-file-name ((,class (:foreground ,string))))
   `(marginalia-file-owner ((,class (:foreground ,warning))))
   `(marginalia-file-priv-dir ((,class (:foreground ,function))))
   `(marginalia-file-priv-exec ((,class (:foreground ,error))))
   `(marginalia-file-priv-link ((,class (:foreground ,keyword))))
   `(marginalia-file-priv-no ((,class (:foreground ,subtle))))
   `(marginalia-file-priv-other ((,class (:foreground ,info))))
   `(marginalia-file-priv-rare ((,class (:foreground ,warning))))
   `(marginalia-file-priv-read ((,class (:foreground ,success))))
   `(marginalia-file-priv-write ((,class (:foreground ,constant))))
   `(marginalia-function ((,class (:foreground ,function))))
   `(marginalia-key ((,class (:foreground ,keyword))))
   `(marginalia-lighter ((,class (:foreground ,comment))))
   `(marginalia-list ((,class (:foreground ,type))))
   `(marginalia-mode ((,class (:foreground ,builtin))))
   `(marginalia-modified ((,class (:foreground ,warning))))
   `(marginalia-null ((,class (:foreground ,subtle))))
   `(marginalia-number ((,class (:foreground ,constant))))
   `(marginalia-size ((,class (:foreground ,info))))
   `(marginalia-string ((,class (:foreground ,string))))
   `(marginalia-symbol ((,class (:foreground ,variable))))
   `(marginalia-true ((,class (:foreground ,success))))
   `(marginalia-type ((,class (:foreground ,type))))
   `(marginalia-value ((,class (:foreground ,constant))))
   `(marginalia-version ((,class (:foreground ,info))))

   ;; Org mode - reduced bold, added italic where appropriate
   `(org-agenda-date ((,class (:foreground ,keyword))))
   `(org-agenda-date-today ((,class (:foreground ,keyword :underline t))))
   `(org-agenda-structure ((,class (:foreground ,builtin))))
   `(org-block ((,class (:background ,bg-bright :foreground ,fg))))
   `(org-block-begin-line ((,class (:background ,bg-darker :foreground ,subtle))))
   `(org-block-end-line ((,class (:background ,bg-darker :foreground ,subtle))))
   `(org-code ((,class (:foreground ,constant))))
   `(org-date ((,class (:foreground ,string :underline t))))
   `(org-document-title ((,class (:foreground ,keyword :height 1.5))))
   `(org-done ((,class (:foreground ,success))))
   `(org-headline-done ((,class (:foreground ,success))))
   `(org-level-1 ((,class (:foreground ,keyword :height 1.3))))
   `(org-level-2 ((,class (:foreground ,function :height 1.2))))
   `(org-level-3 ((,class (:foreground ,type))))
   `(org-level-4 ((,class (:foreground ,variable))))
   `(org-level-5 ((,class (:foreground ,constant))))
   `(org-link ((,class (:foreground ,builtin :underline t))))
   `(org-meta-line ((,class (:foreground ,comment))))
   `(org-priority ((,class (:foreground ,warning))))
   `(org-scheduled ((,class (:foreground ,info))))
   `(org-scheduled-today ((,class (:foreground ,info))))
   `(org-special-keyword ((,class (:foreground ,subtle))))
   `(org-table ((,class (:foreground ,fg))))
   `(org-tag ((,class (:foreground ,keyword))))
   `(org-todo ((,class (:foreground ,error))))
   `(org-upcoming-deadline ((,class (:foreground ,warning))))
   `(org-warning ((,class (:foreground ,error))))
   `(org-verbatim ((,class (:foreground ,constant :slant italic))))
   `(org-verse ((,class (:foreground ,string :slant italic))))
   `(org-checkbox ((,class (:background ,bg-darker :foreground ,fg :box (:line-width 1 :color ,fg)))))
   `(org-checkbox-statistics-todo ((,class (:foreground ,error))))
   `(org-checkbox-statistics-done ((,class (:foreground ,success))))

   ;; Flymake & Flycheck
   `(flymake-error ((,class (:underline (:style wave :color ,error) :foreground ,error))))
   `(flymake-warning ((,class (:underline (:style wave :color ,warning) :foreground ,warning))))
   `(flymake-note ((,class (:underline (:style wave :color ,info) :foreground ,info))))
   `(flymake-fringe-error ((,class (:foreground ,error))))
   `(flymake-fringe-warning ((,class (:foreground ,warning))))
   `(flymake-fringe-note ((,class (:foreground ,info))))
   `(flycheck-error ((,class (:underline (:style wave :color ,error) :foreground ,error))))
   `(flycheck-warning ((,class (:underline (:style wave :color ,warning) :foreground ,warning))))
   `(flycheck-info ((,class (:underline (:style wave :color ,info) :foreground ,info))))
   `(flycheck-fringe-error ((,class (:foreground ,error))))
   `(flycheck-fringe-warning ((,class (:foreground ,warning))))
   `(flycheck-fringe-info ((,class (:foreground ,info))))

   ;; Compilation mode
   `(compilation-error ((,class (:foreground ,error))))
   `(compilation-warning ((,class (:foreground ,warning))))
   `(compilation-info ((,class (:foreground ,info))))
   `(compilation-line-number ((,class (:foreground ,fg))))
   `(compilation-mode-line-fail ((,class (:foreground ,error))))
   `(compilation-mode-line-run ((,class (:foreground ,warning))))
   `(compilation-mode-line-exit ((,class (:foreground ,success))))

   ;; Additional UI elements
   `(header-line ((,class (:background ,bg-bright :foreground ,fg :box nil))))
   `(tooltip ((,class (:background ,bg-darker :foreground ,fg))))
   `(button ((,class (:foreground ,keyword :underline t))))
   `(link ((,class (:foreground ,builtin :underline t))))
   `(link-visited ((,class (:foreground ,builtin :underline t))))
   `(match ((,class (:background ,line-hl :foreground ,fg))))
   `(next-error ((,class (:background ,line-hl :foreground ,fg))))
   `(query-replace ((,class (:background ,line-hl :foreground ,fg))))

   ;; Company completion
   `(company-echo-common ((,class (:foreground ,error))))
   `(company-preview ((,class (:background ,line-hl :foreground ,fg))))
   `(company-preview-common ((,class (:background ,line-hl :foreground ,keyword))))
   `(company-preview-search ((,class (:background ,warning :foreground ,bg))))
   `(company-scrollbar-bg ((,class (:background ,bg-darker))))
   `(company-scrollbar-fg ((,class (:background ,line-hl))))
   `(company-template-field ((,class (:background ,warning :foreground ,bg))))
   `(company-tooltip ((,class (:background ,bg-darker :foreground ,fg))))
   `(company-tooltip-annotation ((,class (:foreground ,info))))
   `(company-tooltip-annotation-selection ((,class (:foreground ,info))))
   `(company-tooltip-common ((,class (:foreground ,keyword))))
   `(company-tooltip-common-selection ((,class (:foreground ,keyword))))
   `(company-tooltip-mouse ((,class (:background ,line-hl))))
   `(company-tooltip-search ((,class (:background ,warning :foreground ,bg))))
   `(company-tooltip-search-selection ((,class (:background ,warning :foreground ,bg))))
   `(company-tooltip-selection ((,class (:background ,line-hl :foreground ,fg))))

   ;; Corfu
   `(corfu-default ((,class (:background ,bg-darker :foreground ,fg))))
   `(corfu-current ((,class (:background ,line-hl :foreground ,fg))))
   `(corfu-border ((,class (:background ,border))))
   `(corfu-annotation ((,class (:foreground ,info))))
   `(corfu-annotation-selection ((,class (:foreground ,info))))
   `(corfu-mouse ((,class (:background ,line-hl))))
   `(corfu-scrollbar-bg ((,class (:background ,bg-darker))))
   `(corfu-scrollbar-fg ((,class (:background ,line-hl))))

   ;; Consult
   `(consult-preview-key ((,class (:foreground ,keyword))))
   `(consult-narrow-indicator ((,class (:foreground ,warning))))

   ;; Basic Completion
   `(completion-common-part ((,class (:foreground ,keyword))))
   `(completion-first-difference ((,class (:foreground ,warning))))

   ;; More ui elements
   `(internal-border ((,class (:background ,bg))))
   `(child-frame-border ((,class (:background ,border))))
   `(highlight-symbol-face ((,class (:background ,line-hl))))
   `(lazy-highlight ((,class (:background ,line-hl :foreground ,fg))))

   ;; Magit (Git interface)
   `(magit-section-heading ((,class (:foreground ,keyword :weight bold))))
   `(magit-section-highlight ((,class (:background ,line-hl))))
   `(magit-section-heading-selection ((,class (:foreground ,keyword :background ,line-hl))))
   `(magit-diff-file-heading ((,class (:foreground ,fg :weight bold))))
   `(magit-diff-file-heading-highlight ((,class (:background ,line-hl :weight bold))))
   `(magit-diff-file-heading-selection ((,class (:background ,line-hl :foreground ,keyword))))
   `(magit-diff-hunk-heading ((,class (:foreground ,builtin :background ,bg-darker))))
   `(magit-diff-hunk-heading-highlight ((,class (:foreground ,builtin :background ,line-hl))))
   `(magit-diff-hunk-heading-selection ((,class (:foreground ,keyword :background ,line-hl))))
   `(magit-diff-context ((,class (:foreground ,subtle))))
   `(magit-diff-context-highlight ((,class (:background ,line-hl :foreground ,fg))))
   `(magit-diff-added ((,class (:foreground ,success :background ,bg))))
   `(magit-diff-added-highlight ((,class (:foreground ,success :background ,line-hl))))
   `(magit-diff-removed ((,class (:foreground ,error :background ,bg))))
   `(magit-diff-removed-highlight ((,class (:foreground ,error :background ,line-hl))))
   `(magit-diff-base ((,class (:foreground ,warning :background ,bg))))
   `(magit-diff-base-highlight ((,class (:foreground ,warning :background ,line-hl))))
   `(magit-diffstat-added ((,class (:foreground ,success))))
   `(magit-diffstat-removed ((,class (:foreground ,error))))
   `(magit-process-ok ((,class (:foreground ,success))))
   `(magit-process-ng ((,class (:foreground ,error))))
   `(magit-log-author ((,class (:foreground ,variable))))
   `(magit-log-date ((,class (:foreground ,subtle))))
   `(magit-log-graph ((,class (:foreground ,subtle))))
   `(magit-sequence-pick ((,class (:foreground ,keyword))))
   `(magit-sequence-stop ((,class (:foreground ,success))))
   `(magit-sequence-part ((,class (:foreground ,warning))))
   `(magit-sequence-head ((,class (:foreground ,info))))
   `(magit-sequence-drop ((,class (:foreground ,error))))
   `(magit-sequence-done ((,class (:foreground ,subtle))))
   `(magit-sequence-onto ((,class (:foreground ,subtle))))
   `(magit-bisect-good ((,class (:foreground ,success))))
   `(magit-bisect-skip ((,class (:foreground ,warning))))
   `(magit-bisect-bad ((,class (:foreground ,error))))
   `(magit-blame-heading ((,class (:background ,bg-darker :foreground ,fg))))
   `(magit-blame-hash ((,class (:background ,bg-darker :foreground ,builtin))))
   `(magit-blame-name ((,class (:background ,bg-darker :foreground ,variable))))
   `(magit-blame-date ((,class (:background ,bg-darker :foreground ,subtle))))
   `(magit-blame-summary ((,class (:background ,bg-darker :foreground ,fg))))
   `(magit-dimmed ((,class (:foreground ,subtle))))
   `(magit-hash ((,class (:foreground ,builtin))))
   `(magit-tag  ((,class (:foreground ,keyword))))
   `(magit-branch-remote ((,class (:foreground ,success))))
   `(magit-branch-local ((,class (:foreground ,info))))
   `(magit-branch-current ((,class (:foreground ,info :box (:line-width 1 :color ,info)))))
   `(magit-head ((,class (:foreground ,info))))
   `(magit-refname ((,class (:foreground ,fg))))
   `(magit-refname-stash ((,class (:foreground ,fg))))
   `(magit-refname-wip ((,class (:foreground ,fg))))
   `(magit-signature-good ((,class (:foreground ,success))))
   `(magit-signature-bad ((,class (:foreground ,error))))
   `(magit-signature-untrusted ((,class (:foreground ,warning))))
   `(magit-signature-expired ((,class (:foreground ,warning))))
   `(magit-signature-revoked ((,class (:foreground ,error))))
   `(magit-signature-error ((,class (:foreground ,error))))
   `(magit-cherry-unmatched ((,class (:foreground ,info))))
   `(magit-cherry-equivalent ((,class (:foreground ,keyword))))
   `(magit-reflog-commit ((,class (:foreground ,success))))
   `(magit-reflog-amend ((,class (:foreground ,keyword))))
   `(magit-reflog-merge ((,class (:foreground ,success))))
   `(magit-reflog-checkout ((,class (:foreground ,info))))
   `(magit-reflog-reset ((,class (:foreground ,error))))
   `(magit-reflog-rebase ((,class (:foreground ,keyword))))
   `(magit-reflog-cherry-pick ((,class (:foreground ,success))))
   `(magit-reflog-remote ((,class (:foreground ,info))))
   `(magit-reflog-other ((,class (:foreground ,subtle))))

   ;; Diff mode
   `(diff-added ((,class (:foreground ,success :background ,bg))))
   `(diff-removed ((,class (:foreground ,error :background ,bg))))
   `(diff-changed ((,class (:foreground ,warning :background ,bg))))
   `(diff-header ((,class (:foreground ,builtin :background ,bg-darker))))
   `(diff-file-header ((,class (:foreground ,fg :weight bold))))
   `(diff-hunk-header ((,class (:foreground ,keyword :background ,bg-darker))))
   `(diff-context ((,class (:foreground ,subtle))))
   `(diff-function ((,class (:foreground ,function))))
   `(diff-nonexistent ((,class (:foreground ,error))))
   `(diff-refine-added ((,class (:foreground ,success :background ,line-hl :weight bold))))
   `(diff-refine-removed ((,class (:foreground ,error :background ,line-hl :weight bold))))
   `(diff-refine-changed ((,class (:foreground ,warning :background ,line-hl :weight bold))))

   ;; Dired
   `(dired-directory ((,class (:foreground ,info :weight bold))))
   `(dired-symlink ((,class (:foreground ,keyword))))
   `(dired-special ((,class (:foreground ,builtin))))
   `(dired-mark ((,class (:foreground ,success :weight bold))))
   `(dired-marked ((,class (:foreground ,success :background ,line-hl))))
   `(dired-flagged ((,class (:foreground ,error :weight bold))))
   `(dired-header ((,class (:foreground ,keyword :weight bold))))
   `(dired-warning ((,class (:foreground ,warning))))
   `(dired-perm-write ((,class (:foreground ,fg))))
   `(dired-set-id ((,class (:foreground ,keyword))))
   `(dired-ignored ((,class (:foreground ,subtle))))

   ;; Markdown
   `(markdown-header-face-1 ((,class (:foreground ,keyword :weight bold :height 1.3))))
   `(markdown-header-face-2 ((,class (:foreground ,function :weight bold :height 1.2))))
   `(markdown-header-face-3 ((,class (:foreground ,type :weight bold))))
   `(markdown-header-face-4 ((,class (:foreground ,variable :weight bold))))
   `(markdown-header-face-5 ((,class (:foreground ,constant))))
   `(markdown-header-face-6 ((,class (:foreground ,builtin))))
   `(markdown-header-delimiter-face ((,class (:foreground ,subtle))))
   `(markdown-bold-face ((,class (:weight bold))))
   `(markdown-italic-face ((,class (:slant italic))))
   `(markdown-link-face ((,class (:foreground ,builtin :underline t))))
   `(markdown-url-face ((,class (:foreground ,builtin :underline t))))
   `(markdown-inline-code-face ((,class (:foreground ,constant :background ,line-hl))))
   `(markdown-pre-face ((,class (:foreground ,fg :background ,line-hl))))
   `(markdown-code-face ((,class (:foreground ,fg :background ,line-hl))))
   `(markdown-language-keyword-face ((,class (:foreground ,keyword))))
   `(markdown-list-face ((,class (:foreground ,keyword))))
   `(markdown-blockquote-face ((,class (:foreground ,comment :slant italic))))
   `(markdown-html-tag-name-face ((,class (:foreground ,keyword))))
   `(markdown-html-attr-name-face ((,class (:foreground ,type))))
   `(markdown-html-tag-delimiter-face ((,class (:foreground ,subtle))))
   `(markdown-metadata-key-face ((,class (:foreground ,keyword))))
   `(markdown-metadata-value-face ((,class (:foreground ,string))))
   `(markdown-gfm-checkbox-face ((,class (:foreground ,keyword))))
   `(markdown-strike-through-face ((,class (:strike-through t))))
   `(markdown-markup-face ((,class (:foreground ,subtle))))

   ;; Rainbow delimiters
   `(rainbow-delimiters-depth-1-face ((,class (:foreground ,function))))
   `(rainbow-delimiters-depth-2-face ((,class (:foreground ,type))))
   `(rainbow-delimiters-depth-3-face ((,class (:foreground ,builtin))))
   `(rainbow-delimiters-depth-4-face ((,class (:foreground ,info))))
   `(rainbow-delimiters-depth-5-face ((,class (:foreground ,warning))))
   `(rainbow-delimiters-depth-6-face ((,class (:foreground ,constant))))
   `(rainbow-delimiters-depth-7-face ((,class (:foreground ,variable))))
   `(rainbow-delimiters-depth-8-face ((,class (:foreground ,keyword))))
   `(rainbow-delimiters-depth-9-face ((,class (:foreground ,success))))
   `(rainbow-delimiters-unmatched-face ((,class (:foreground ,error :weight bold))))
   `(rainbow-delimiters-mismatched-face ((,class (:foreground ,error :weight bold))))

   ;; Which-key
   `(which-key-key-face ((,class (:foreground ,keyword))))
   `(which-key-separator-face ((,class (:foreground ,subtle))))
   `(which-key-note-face ((,class (:foreground ,comment))))
   `(which-key-command-description-face ((,class (:foreground ,fg))))
   `(which-key-local-map-description-face ((,class (:foreground ,variable))))
   `(which-key-group-description-face ((,class (:foreground ,info))))
   `(which-key-highlighted-command-face ((,class (:foreground ,warning :weight bold))))
   `(which-key-special-key-face ((,class (:foreground ,error))))

   ;; Eglot/LSP
   `(eglot-highlight-symbol-face ((,class (:background ,line-hl :weight bold))))
   `(eglot-mode-line ((,class (:foreground ,info))))
   `(eglot-diagnostic-tag-unnecessary-face ((,class (:foreground ,subtle :strike-through t))))
   `(eglot-diagnostic-tag-deprecated-face ((,class (:foreground ,subtle :strike-through t))))

   ;; Tree-sitter
   `(tree-sitter-hl-face:function ((,class (:foreground ,function :slant italic))))
   `(tree-sitter-hl-face:function.call ((,class (:foreground ,function))))
   `(tree-sitter-hl-face:function.method ((,class (:foreground ,function :slant italic))))
   `(tree-sitter-hl-face:type ((,class (:foreground ,type))))
   `(tree-sitter-hl-face:type.builtin ((,class (:foreground ,type))))
   `(tree-sitter-hl-face:constructor ((,class (:foreground ,function))))
   `(tree-sitter-hl-face:variable ((,class (:foreground ,variable))))
   `(tree-sitter-hl-face:variable.builtin ((,class (:foreground ,builtin))))
   `(tree-sitter-hl-face:variable.parameter ((,class (:foreground ,variable))))
   `(tree-sitter-hl-face:variable.special ((,class (:foreground ,keyword))))
   `(tree-sitter-hl-face:property ((,class (:foreground ,constant))))
   `(tree-sitter-hl-face:property.definition ((,class (:foreground ,constant))))
   `(tree-sitter-hl-face:comment ((,class (:foreground ,comment :slant italic))))
   `(tree-sitter-hl-face:doc ((,class (:foreground ,comment :slant italic))))
   `(tree-sitter-hl-face:string ((,class (:foreground ,string))))
   `(tree-sitter-hl-face:string.special ((,class (:foreground ,builtin))))
   `(tree-sitter-hl-face:escape ((,class (:foreground ,builtin))))
   `(tree-sitter-hl-face:embedded ((,class (:foreground ,fg))))
   `(tree-sitter-hl-face:keyword ((,class (:foreground ,keyword :slant italic))))
   `(tree-sitter-hl-face:operator ((,class (:foreground ,keyword))))
   `(tree-sitter-hl-face:label ((,class (:foreground ,constant))))
   `(tree-sitter-hl-face:constant ((,class (:foreground ,constant))))
   `(tree-sitter-hl-face:constant.builtin ((,class (:foreground ,constant))))
   `(tree-sitter-hl-face:number ((,class (:foreground ,constant))))
   `(tree-sitter-hl-face:punctuation ((,class (:foreground ,fg))))
   `(tree-sitter-hl-face:punctuation.bracket ((,class (:foreground ,fg))))
   `(tree-sitter-hl-face:punctuation.delimiter ((,class (:foreground ,fg))))
   `(tree-sitter-hl-face:punctuation.special ((,class (:foreground ,keyword))))
   `(tree-sitter-hl-face:tag ((,class (:foreground ,keyword))))
   `(tree-sitter-hl-face:attribute ((,class (:foreground ,type))))

   ;; Treemacs
   `(treemacs-root-face ((,class (:foreground ,keyword :weight bold :height 1.2))))
   `(treemacs-directory-face ((,class (:foreground ,info))))
   `(treemacs-directory-collapsed-face ((,class (:foreground ,info))))
   `(treemacs-file-face ((,class (:foreground ,fg))))
   `(treemacs-git-modified-face ((,class (:foreground ,warning))))
   `(treemacs-git-added-face ((,class (:foreground ,success))))
   `(treemacs-git-conflict-face ((,class (:foreground ,error))))
   `(treemacs-git-untracked-face ((,class (:foreground ,info))))
   `(treemacs-git-ignored-face ((,class (:foreground ,subtle))))
   `(treemacs-tags-face ((,class (:foreground ,keyword))))
   `(treemacs-help-title-face ((,class (:foreground ,keyword :weight bold))))
   `(treemacs-help-column-face ((,class (:foreground ,info))))
   `(treemacs-term-node-face ((,class (:foreground ,function))))
   `(treemacs-fringe-indicator-face ((,class (:foreground ,keyword))))

   ;; Eshell
   `(eshell-prompt ((,class (:foreground ,keyword :weight bold))))
   `(eshell-ls-archive ((,class (:foreground ,warning))))
   `(eshell-ls-backup ((,class (:foreground ,subtle))))
   `(eshell-ls-clutter ((,class (:foreground ,error))))
   `(eshell-ls-directory ((,class (:foreground ,info :weight bold))))
   `(eshell-ls-executable ((,class (:foreground ,success))))
   `(eshell-ls-missing ((,class (:foreground ,error))))
   `(eshell-ls-product ((,class (:foreground ,warning))))
   `(eshell-ls-readonly ((,class (:foreground ,subtle))))
   `(eshell-ls-special ((,class (:foreground ,builtin))))
   `(eshell-ls-symlink ((,class (:foreground ,keyword))))
   `(eshell-ls-unreadable ((,class (:foreground ,error))))
   ))

(provide-theme 'sapporo-night-rebuilt)
;;; sapporo-night-theme.el ends here
