;;; sapporo-night-theme.el --- A bright dark theme, inspired by Tokyo Night Storm and Nord -*- lexical-binding: t; -*-

;; Copyright (C) 2025
;; Author: SoraTenshi
;; Version: 0.0.1
;; URL: https://github.com/yourname/sapporo-night-theme

;;; Commentary:
;; This file defines the Sapporo Night theme, a bright dark theme with purple-blue tones,
;; inspired by Tokyo Night Storm and Nord aesthetics.
;;; Code:

(deftheme sapporo-night
  "A bright dark theme with purple-blue tones, inspired by Tokyo Night Storm and Nord aesthetics.")

(let ((class '((class color) (min-colors 89)))
      (bg "#2a2947")
      (bg-bright "#51518B")
      (bg-darker "#202037")
      (fg "#a0b7eb")
      (fg-alt "#8bbaf3")
      (comment "#5FACF2")
      (keyword "#ab8bf7")
      (function "#9ab1fa")
      (string "#b0d4ff")
      (variable "#8bbaf3")
      (constant "#a9c7ff")
      (builtin "#94b5f0")
      (type "#8ea1ff")
      (line-hl "#33325d")
      (selection "#3b3b80")
      (cursor "#bb9af7")
      (error "#c678dd")
      (warning "#9dc8f8")
      (info "#87a3d4")
      (success "#56d8f4")
      (border "#404070")
      (subtle "#565f89")
      (faded "#4a5073"))

  (custom-theme-set-faces
   'sapporo-night

   ;; Base
   `(default ((,class (:background ,bg :foreground ,fg))))
   `(cursor ((,class (:background ,cursor))))
   `(region ((,class (:background ,selection :foreground ,fg))))
   `(secondary-selection ((,class (:background ,line-hl :foreground ,fg))))
   `(highlight ((,class (:background ,line-hl :foreground ,bg))))
   `(hl-line ((,class (:background nil :box (:line-width -1 :color ,line-hl)))))
   `(fringe ((,class (:background ,bg :foreground ,subtle))))
   `(vertical-border ((,class (:foreground ,border))))
   `(window-divider ((,class (:foreground ,border))))
   `(window-divider-first-pixel ((,class (:foreground ,border))))
   `(window-divider-last-pixel ((,class (:foreground ,border))))
   `(file-name-shadow ((,class (:foreground ,faded))))
   `(shadow ((,class (:foreground ,faded))))
   `(link ((,class (:foreground ,builtin :underline t))))
   `(link-visited ((,class (:foreground ,builtin :underline t))))

   ;; Font lock
   `(font-lock-builtin-face ((,class (:inherit nil :foreground ,builtin))))
   `(font-lock-comment-face ((,class (:inherit nil :foreground ,comment :slant italic))))
   `(font-lock-comment-delimiter-face ((,class (:inherit nil :foreground ,comment :slant italic))))
   `(font-lock-constant-face ((,class (:inherit nil :foreground ,constant))))
   `(font-lock-function-name-face ((,class (:inherit nil :foreground ,function :slant italic))))
   `(font-lock-keyword-face ((,class (:inherit nil :foreground ,keyword :slant italic))))
   `(font-lock-string-face ((,class (:inherit nil :foreground ,string))))
   `(font-lock-type-face ((,class (:inherit nil :foreground ,type))))
   `(font-lock-variable-name-face ((,class (:inherit nil :foreground ,variable))))
   `(font-lock-warning-face ((,class (:inherit nil :foreground ,warning))))
   `(font-lock-doc-face ((,class (:inherit nil :foreground ,comment :slant italic))))
   `(font-lock-preprocessor-face ((,class (:inherit nil :foreground ,builtin))))
   `(font-lock-negation-char-face ((,class (:inherit nil :foreground ,error))))
   `(font-lock-regexp-grouping-backslash ((,class (:inherit nil :foreground ,keyword))))
   `(font-lock-regexp-grouping-construct ((,class (:inherit nil :foreground ,constant))))
   `(font-lock-number-face ((,class (:inherit font-lock-constant-face))))
   `(font-lock-operator-face ((,class (:foreground ,keyword))))
   `(font-lock-delimiter-face ((,class (:foreground ,subtle))))
   `(font-lock-punctuation-face ((,class (:foreground ,subtle))))
   `(font-lock-escape-face ((,class (:foreground ,warning))))

   ;; Minibuffer / echo area
   `(minibuffer-prompt ((,class (:foreground ,keyword))))
   `(echo-area-message ((,class (:foreground ,fg))))

   ;; Mode line
   `(mode-line ((,class (:background ,line-hl :foreground ,fg :box nil))))
   `(mode-line-inactive ((,class (:background ,bg :foreground ,subtle :box nil))))
   `(mode-line-buffer-id ((,class (:foreground ,keyword))))

   ;; Line numbers
   `(line-number ((,class (:background ,bg :foreground ,subtle))))
   `(line-number-current-line ((,class (:inherit line-number :foreground ,fg :weight bold))))

   ;; Parens
   `(show-paren-match ((,class (:background ,line-hl :foreground ,fg :box (:line-width -1 :color ,keyword)))))
   `(show-paren-mismatch ((,class (:background ,error :foreground ,bg :weight bold))))

   ;; Search
   `(isearch ((,class (:background ,keyword :foreground ,bg :weight bold))))
   `(lazy-highlight ((,class (:background ,line-hl :foreground ,fg))))
   `(match ((,class (:background ,info :foreground ,bg :weight bold))))

   ;; Status faces
   `(error ((,class (:foreground ,error))))
   `(warning ((,class (:foreground ,warning))))
   `(success ((,class (:foreground ,success))))

   `(fill-column-indicator ((,class (:foreground ,faded :height 1.2))))

   ;; Whitespace
   `(whitespace-space ((,class (:foreground ,faded))))
   `(whitespace-tab ((,class (:foreground ,faded :background ,bg))))
   `(whitespace-newline ((,class (:foreground ,faded))))
   `(whitespace-trailing ((,class (:background ,error :foreground ,bg))))
   `(whitespace-line ((,class (:background nil :foreground nil))))
   `(whitespace-space-before-tab ((,class (:background ,bg :foreground ,warning :underline t))))
   `(whitespace-indentation ((,class (:background ,bg :foreground ,subtle))))
   `(whitespace-empty ((,class (:background ,bg-darker))))
   `(whitespace-space-after-tab ((,class (:background ,bg :foreground ,warning :underline t))))
   `(whitespace-missing-newline-at-eof ((,class (:background ,error :foreground ,bg))))
   `(whitespace-big-indent ((,class (:background ,bg :foreground ,warning))))
   `(whitespace-hspace ((,class (:foreground ,faded :background ,bg))))

   ;; Vertico
   `(vertico-current ((,class (:background ,line-hl :foreground ,fg))))
   `(vertico-group-title ((,class (:foreground ,keyword))))
   `(vertico-group-separator ((,class (:foreground ,border))))
   `(vertico-multiline ((,class (:foreground ,comment))))

   ;; Orderless
   `(orderless-match-face-0 ((,class (:foreground ,keyword :weight bold))))
   `(orderless-match-face-1 ((,class (:foreground ,warning :weight bold))))
   `(orderless-match-face-2 ((,class (:foreground ,info :weight bold))))
   `(orderless-match-face-3 ((,class (:foreground ,success :weight bold))))
   `(orderless-match-face-4 ((,class (:foreground ,error :weight bold))))
   `(orderless-match-face-5 ((,class (:foreground ,keyword :weight bold))))

   ;; Marginalia
   `(marginalia-archive ((,class (:foreground ,info))))
   `(marginalia-char ((,class (:foreground ,constant))))
   `(marginalia-date ((,class (:foreground ,builtin))))
   `(marginalia-documentation ((,class (:foreground ,comment :slant italic))))
   `(marginalia-file-name ((,class (:foreground ,string))))
   `(marginalia-file-owner ((,class (:foreground ,warning))))
   `(marginalia-file-priv-dir ((,class (:foreground ,function))))
   `(marginalia-file-priv-exec ((,class (:foreground ,error))))
   `(marginalia-file-priv-link ((,class (:foreground ,keyword))))
   `(marginalia-file-priv-no ((,class (:foreground ,subtle))))
   `(marginalia-file-priv-other ((,class (:foreground ,info))))
   `(marginalia-file-priv-rare ((,class (:foreground ,warning))))
   `(marginalia-file-priv-read ((,class (:foreground ,success))))
   `(marginalia-file-priv-write ((,class (:foreground ,constant))))
   `(marginalia-function ((,class (:foreground ,function))))
   `(marginalia-key ((,class (:foreground ,keyword))))
   `(marginalia-lighter ((,class (:foreground ,comment))))
   `(marginalia-list ((,class (:foreground ,type))))
   `(marginalia-mode ((,class (:foreground ,builtin))))
   `(marginalia-modified ((,class (:foreground ,warning))))
   `(marginalia-null ((,class (:foreground ,subtle))))
   `(marginalia-number ((,class (:foreground ,constant))))
   `(marginalia-size ((,class (:foreground ,info))))
   `(marginalia-string ((,class (:foreground ,string))))
   `(marginalia-symbol ((,class (:foreground ,variable))))
   `(marginalia-true ((,class (:foreground ,success))))
   `(marginalia-type ((,class (:foreground ,type))))
   `(marginalia-value ((,class (:foreground ,constant))))
   `(marginalia-version ((,class (:foreground ,info))))

   ;; Org
   `(org-agenda-date ((,class (:foreground ,keyword))))
   `(org-agenda-date-today ((,class (:foreground ,keyword :underline t))))
   `(org-agenda-structure ((,class (:foreground ,builtin))))
   `(org-block ((,class (:background ,bg-darker :foreground ,fg))))
   `(org-block-begin-line ((,class (:background ,bg-bright :foreground ,subtle))))
   `(org-block-end-line ((,class (:background ,bg-bright :foreground ,subtle))))
   `(org-code ((,class (:foreground ,constant))))
   `(org-date ((,class (:foreground ,string :underline t))))
   `(org-document-title ((,class (:foreground ,keyword :height 1.5))))
   `(org-done ((,class (:foreground ,success))))
   `(org-headline-done ((,class (:foreground ,success))))
   `(org-level-1 ((,class (:foreground ,keyword :height 1.3))))
   `(org-level-2 ((,class (:foreground ,function :height 1.2))))
   `(org-level-3 ((,class (:foreground ,type))))
   `(org-level-4 ((,class (:foreground ,variable))))
   `(org-level-5 ((,class (:foreground ,constant))))
   `(org-link ((,class (:foreground ,builtin :underline t))))
   `(org-meta-line ((,class (:foreground ,comment))))
   `(org-priority ((,class (:foreground ,warning))))
   `(org-scheduled ((,class (:foreground ,info))))
   `(org-scheduled-today ((,class (:foreground ,info))))
   `(org-special-keyword ((,class (:foreground ,subtle))))
   `(org-table ((,class (:foreground ,fg))))
   `(org-tag ((,class (:foreground ,keyword))))
   `(org-todo ((,class (:foreground ,error))))
   `(org-upcoming-deadline ((,class (:foreground ,warning))))
   `(org-warning ((,class (:foreground ,error))))
   `(org-verbatim ((,class (:foreground ,constant :slant italic))))
   `(org-verse ((,class (:foreground ,string :slant italic))))
   `(org-checkbox ((,class (:background ,bg-darker :foreground ,fg :box (:line-width 1 :color ,fg)))))
   `(org-checkbox-statistics-todo ((,class (:foreground ,error))))
   `(org-checkbox-statistics-done ((,class (:foreground ,success))))

   ;; Diagnostics
   `(flymake-error ((,class (:underline (:style wave :color ,error) :foreground ,error))))
   `(flymake-warning ((,class (:underline (:style wave :color ,warning) :foreground ,warning))))
   `(flymake-note ((,class (:underline (:style wave :color ,info) :foreground ,info))))
   `(flymake-fringe-error ((,class (:foreground ,error))))
   `(flymake-fringe-warning ((,class (:foreground ,warning))))
   `(flymake-fringe-note ((,class (:foreground ,info))))
   `(flycheck-error ((,class (:underline (:style wave :color ,error) :foreground ,error))))
   `(flycheck-warning ((,class (:underline (:style wave :color ,warning) :foreground ,warning))))
   `(flycheck-info ((,class (:underline (:style wave :color ,info) :foreground ,info))))
   `(flycheck-fringe-error ((,class (:foreground ,error))))
   `(flycheck-fringe-warning ((,class (:foreground ,warning))))
   `(flycheck-fringe-info ((,class (:foreground ,info))))

   ;; Compilation
   `(compilation-error ((,class (:foreground ,error))))
   `(compilation-warning ((,class (:foreground ,warning))))
   `(compilation-info ((,class (:foreground ,info))))
   `(compilation-line-number ((,class (:foreground ,fg))))
   `(compilation-mode-line-fail ((,class (:foreground ,error))))
   `(compilation-mode-line-run ((,class (:foreground ,warning))))
   `(compilation-mode-line-exit ((,class (:foreground ,success))))

   ;; UI bits
   `(header-line ((,class (:background ,bg-bright :foreground ,fg :box nil))))
   `(tooltip ((,class (:background ,bg-darker :foreground ,fg))))
   `(button ((,class (:foreground ,keyword :underline t))))
   `(next-error ((,class (:background ,line-hl :foreground ,fg))))
   `(query-replace ((,class (:background ,line-hl :foreground ,fg))))

   ;; Company
   `(company-echo-common ((,class (:foreground ,error))))
   `(company-preview ((,class (:background ,line-hl :foreground ,fg))))
   `(company-preview-common ((,class (:background ,line-hl :foreground ,keyword))))
   `(company-preview-search ((,class (:background ,warning :foreground ,bg))))
   `(company-scrollbar-bg ((,class (:background ,bg-darker))))
   `(company-scrollbar-fg ((,class (:background ,line-hl))))
   `(company-template-field ((,class (:background ,warning :foreground ,bg))))
   `(company-tooltip ((,class (:background ,bg-darker :foreground ,fg))))
   `(company-tooltip-annotation ((,class (:foreground ,info))))
   `(company-tooltip-annotation-selection ((,class (:foreground ,info))))
   `(company-tooltip-common ((,class (:foreground ,keyword))))
   `(company-tooltip-common-selection ((,class (:foreground ,keyword))))
   `(company-tooltip-mouse ((,class (:background ,line-hl))))
   `(company-tooltip-search ((,class (:background ,warning :foreground ,bg))))
   `(company-tooltip-search-selection ((,class (:background ,warning :foreground ,bg))))
   `(company-tooltip-selection ((,class (:background ,line-hl :foreground ,fg))))

   ;; Corfu
   `(corfu-default ((,class (:background ,bg-darker :foreground ,fg))))
   `(corfu-current ((,class (:background ,line-hl :foreground ,fg))))
   `(corfu-border ((,class (:background ,border :foreground ,border))))
   `(corfu-annotation ((,class (:foreground ,info))))
   `(corfu-annotation-selection ((,class (:foreground ,info))))
   `(corfu-mouse ((,class (:background ,line-hl))))
   `(corfu-scrollbar-bg ((,class (:background ,bg-darker))))
   `(corfu-scrollbar-fg ((,class (:background ,line-hl))))

   ;; Consult
   `(consult-key ((,class (:foreground ,keyword))))
   `(consult-narrow-indicator ((,class (:foreground ,warning))))
   `(consult-preview-match ((,class (:background ,line-hl :foreground ,fg))))

   ;; Completion basics
   `(completion-common-part ((,class (:foreground ,keyword))))
   `(completion-first-difference ((,class (:foreground ,warning))))

   ;; Borders
   `(internal-border ((,class (:background ,border))))
   `(child-frame-border ((,class (:foreground ,border))))
   `(highlight-symbol-face ((,class (:background ,line-hl))))

   ;; Tree-sitter highlight (for users of tree-sitter-hl)
   `(tree-sitter-hl-face:type ((,class (:foreground ,type))))
   `(tree-sitter-hl-face:type.builtin ((,class (:foreground ,builtin))))
   `(tree-sitter-hl-face:interface ((,class (:foreground ,type))))
   `(tree-sitter-hl-face:struct ((,class (:foreground ,type))))
   `(tree-sitter-hl-face:enum ((,class (:foreground ,type))))
   `(tree-sitter-hl-face:constant ((,class (:foreground ,constant))))
   `(tree-sitter-hl-face:number ((,class (:foreground ,constant))))
   `(tree-sitter-hl-face:string ((,class (:foreground ,string))))
   `(tree-sitter-hl-face:escape ((,class (:foreground ,warning))))
   `(tree-sitter-hl-face:function ((,class (:foreground ,function :slant italic))))
   `(tree-sitter-hl-face:function.builtin ((,class (:foreground ,builtin))))
   `(tree-sitter-hl-face:method ((,class (:foreground ,function :slant italic))))
   `(tree-sitter-hl-face:property ((,class (:foreground ,variable))))
   `(tree-sitter-hl-face:variable ((,class (:foreground ,variable))))
   `(tree-sitter-hl-face:variable.builtin ((,class (:foreground ,builtin))))
   `(tree-sitter-hl-face:attribute ((,class (:foreground ,info))))
   `(tree-sitter-hl-face:label ((,class (:foreground ,type))))
   `(tree-sitter-hl-face:operator ((,class (:foreground ,keyword))))
   `(tree-sitter-hl-face:punctuation ((,class (:foreground ,subtle))))
   `(tree-sitter-hl-face:tag ((,class (:foreground ,keyword))))
   `(tree-sitter-hl-face:attribute ((,class (:foreground ,type))))

   ;; ERC (IRC Client)
   `(erc-default-face ((,class (:foreground ,fg))))
   `(erc-input-face ((,class (:foreground ,cursor :weight bold))))
   `(erc-prompt-face ((,class (:foreground ,cursor :weight bold))))
   `(erc-command-indicator-face ((,class (:foreground ,cursor :weight bold))))
   `(erc-current-nick-face ((,class (:foreground ,cursor :weight bold))))
   `(erc-my-nick-face ((,class (:foreground ,cursor :weight bold))))
   `(erc-my-nick-prefix-face ((,class (:foreground ,cursor :weight bold))))
   `(erc-nick-default-face ((,class (:foreground ,function))))
   `(erc-nick-msg-face ((,class (:foreground ,warning :weight bold))))
   `(erc-direct-msg-face ((,class (:foreground ,warning))))
   `(erc-pal-face ((,class (:foreground ,type :weight bold))))
   `(erc-fool-face ((,class (:foreground ,faded))))
   `(erc-dangerous-host-face ((,class (:foreground ,error :weight bold))))
   `(erc-timestamp-face ((,class (:foreground ,subtle))))
   `(erc-notice-face ((,class (:foreground ,error :weight bold))))
   `(erc-error-face ((,class (:foreground ,error :weight bold))))
   `(erc-action-face ((,class (:foreground ,variable :slant italic))))
   `(erc-button ((,class (:foreground ,builtin :underline t))))
   `(erc-keyword-face ((,class (:foreground ,keyword :weight bold))))
   `(erc-header-line ((,class (:background ,bg-bright :foreground ,fg))))
   `(erc-join-face ((,class (:foreground ,success :weight bold))))
   `(erc-part-face ((,class (:foreground ,warning :weight bold))))
   `(erc-quit-face ((,class (:foreground ,constant :weight bold))))
   `(erc-nick-change-face ((,class (:foreground ,info :weight bold))))
   `(erc-ctcp-face ((,class (:foreground ,constant))))
   `(erc-dcc-face ((,class (:foreground ,constant))))
   `(erc-underline-face ((,class (:underline t))))
   `(erc-mode-indicator-face ((,class (:foreground ,keyword :weight bold))))
   `(erc-away-face ((,class (:foreground ,faded :slant italic))))
   `(erc-topic-face ((,class (:foreground ,type :slant italic))))
   `(erc-op-face ((,class (:foreground ,error :weight bold))))
   `(erc-voice-face ((,class (:foreground ,warning))))
   `(erc-fill-wrap-merge-indicator-face ((,class (:foreground ,subtle))))
   `(erc-bold-face ((,class (:weight bold))))
   `(erc-inverse-face ((,class (:background ,fg :foreground ,bg))))
   `(erc-match-face ((,class (:background ,line-hl :foreground ,keyword :weight bold))))

   `(hel-normal-state-fake-cursor ((,class (:background ,type))))
   `(hel-insert-state-fake-cursor ((,class (:background ,type))))
   `(hel-extend-selection-cursor ((,class (:foreground ,cursor))))
   `(hel-search-highlight ((,class (:foreground ,cursor))))
   `(hel-mode-line-cursors-indicator ((,class (:foreground ,cursor))))

   ;; Scroll bars
   `(scroll-bar ((,class (:background ,bg-darker :foreground ,line-hl))))
   ))

(provide-theme 'sapporo-night)
;;; sapporo-night-theme.el --- A bright dark theme, inspired by Tokyo Night Storm and Nord -*- lexical-binding: t; -*-

;; Copyright (C) 2025
;; Author: SoraTenshi
;; Version: 0.0.1
;; URL: https://github.com/yourname/sapporo-night-theme

;;; Commentary:
;; This file defines the Sapporo Night theme, a bright dark theme with purple-blue tones,
;; inspired by Tokyo Night Storm and Nord aesthetics.
;;; Code:

(deftheme sapporo-night
  "A bright dark theme with purple-blue tones, inspired by Tokyo Night Storm and Nord aesthetics.")

(let ((class '((class color) (min-colors 89)))
      (bg "#2a2947")
      (bg-bright "#51518B")
      (bg-darker "#202037")
      (fg "#a0b7eb")
      (fg-alt "#8bbaf3")
      (comment "#5FACF2")
      (keyword "#ab8bf7")
      (function "#9ab1fa")
      (string "#b0d4ff")
      (variable "#8bbaf3")
      (constant "#a9c7ff")
      (builtin "#94b5f0")
      (type "#8ea1ff")
      (line-hl "#33325d")
      (selection "#3b3b80")
      (cursor "#bb9af7")
      (error "#c678dd")
      (warning "#9dc8f8")
      (info "#87a3d4")
      (success "#56d8f4")
      (border "#404070")
      (subtle "#565f89")
      (faded "#4a5073"))

  (custom-theme-set-faces
   'sapporo-night

   ;; Base
   `(default ((,class (:background ,bg :foreground ,fg))))
   `(cursor ((,class (:background ,cursor))))
   `(region ((,class (:background ,selection :foreground ,fg))))
   `(secondary-selection ((,class (:background ,line-hl :foreground ,fg))))
   `(highlight ((,class (:background ,line-hl :foreground ,bg))))
   `(hl-line ((,class (:background nil :box (:line-width -1 :color ,line-hl)))))
   `(fringe ((,class (:background ,bg :foreground ,subtle))))
   `(vertical-border ((,class (:foreground ,border))))
   `(window-divider ((,class (:foreground ,border))))
   `(window-divider-first-pixel ((,class (:foreground ,border))))
   `(window-divider-last-pixel ((,class (:foreground ,border))))
   `(file-name-shadow ((,class (:foreground ,faded))))
   `(shadow ((,class (:foreground ,faded))))
   `(link ((,class (:foreground ,builtin :underline t))))
   `(link-visited ((,class (:foreground ,builtin :underline t))))

   ;; Font lock
   `(font-lock-builtin-face ((,class (:inherit nil :foreground ,builtin))))
   `(font-lock-comment-face ((,class (:inherit nil :foreground ,comment :slant italic))))
   `(font-lock-comment-delimiter-face ((,class (:inherit nil :foreground ,comment :slant italic))))
   `(font-lock-constant-face ((,class (:inherit nil :foreground ,constant))))
   `(font-lock-function-name-face ((,class (:inherit nil :foreground ,function :slant italic))))
   `(font-lock-keyword-face ((,class (:inherit nil :foreground ,keyword :slant italic))))
   `(font-lock-string-face ((,class (:inherit nil :foreground ,string))))
   `(font-lock-type-face ((,class (:inherit nil :foreground ,type))))
   `(font-lock-variable-name-face ((,class (:inherit nil :foreground ,variable))))
   `(font-lock-warning-face ((,class (:inherit nil :foreground ,warning))))
   `(font-lock-doc-face ((,class (:inherit nil :foreground ,comment :slant italic))))
   `(font-lock-preprocessor-face ((,class (:inherit nil :foreground ,builtin))))
   `(font-lock-negation-char-face ((,class (:inherit nil :foreground ,error))))
   `(font-lock-regexp-grouping-backslash ((,class (:inherit nil :foreground ,keyword))))
   `(font-lock-regexp-grouping-construct ((,class (:inherit nil :foreground ,constant))))
   `(font-lock-number-face ((,class (:inherit font-lock-constant-face))))
   `(font-lock-operator-face ((,class (:foreground ,keyword))))
   `(font-lock-delimiter-face ((,class (:foreground ,subtle))))
   `(font-lock-punctuation-face ((,class (:foreground ,subtle))))
   `(font-lock-escape-face ((,class (:foreground ,warning))))

   ;; Minibuffer / echo area
   `(minibuffer-prompt ((,class (:foreground ,keyword))))
   `(echo-area-message ((,class (:foreground ,fg))))

   ;; Mode line
   `(mode-line ((,class (:background ,line-hl :foreground ,fg :box nil))))
   `(mode-line-inactive ((,class (:background ,bg :foreground ,subtle :box nil))))
   `(mode-line-buffer-id ((,class (:foreground ,keyword))))

   ;; Line numbers
   `(line-number ((,class (:background ,bg :foreground ,subtle))))
   `(line-number-current-line ((,class (:inherit line-number :foreground ,fg :weight bold))))

   ;; Parens
   `(show-paren-match ((,class (:background ,line-hl :foreground ,fg :box (:line-width -1 :color ,keyword)))))
   `(show-paren-mismatch ((,class (:background ,error :foreground ,bg :weight bold))))

   ;; Search
   `(isearch ((,class (:background ,keyword :foreground ,bg :weight bold))))
   `(lazy-highlight ((,class (:background ,line-hl :foreground ,fg))))
   `(match ((,class (:background ,info :foreground ,bg :weight bold))))

   ;; Status faces
   `(error ((,class (:foreground ,error))))
   `(warning ((,class (:foreground ,warning))))
   `(success ((,class (:foreground ,success))))

   `(fill-column-indicator ((,class (:foreground ,faded :height 1.2))))

   ;; Whitespace
   `(whitespace-space ((,class (:foreground ,faded))))
   `(whitespace-tab ((,class (:foreground ,faded :background ,bg))))
   `(whitespace-newline ((,class (:foreground ,faded))))
   `(whitespace-trailing ((,class (:background ,error :foreground ,bg))))
   `(whitespace-line ((,class (:background nil :foreground nil))))
   `(whitespace-space-before-tab ((,class (:background ,bg :foreground ,warning :underline t))))
   `(whitespace-indentation ((,class (:background ,bg :foreground ,subtle))))
   `(whitespace-empty ((,class (:background ,bg-darker))))
   `(whitespace-space-after-tab ((,class (:background ,bg :foreground ,warning :underline t))))
   `(whitespace-missing-newline-at-eof ((,class (:background ,error :foreground ,bg))))
   `(whitespace-big-indent ((,class (:background ,bg :foreground ,warning))))
   `(whitespace-hspace ((,class (:foreground ,faded :background ,bg))))

   ;; Vertico
   `(vertico-current ((,class (:background ,line-hl :foreground ,fg))))
   `(vertico-group-title ((,class (:foreground ,keyword))))
   `(vertico-group-separator ((,class (:foreground ,border))))
   `(vertico-multiline ((,class (:foreground ,comment))))

   ;; Orderless
   `(orderless-match-face-0 ((,class (:foreground ,keyword :weight bold))))
   `(orderless-match-face-1 ((,class (:foreground ,warning :weight bold))))
   `(orderless-match-face-2 ((,class (:foreground ,info :weight bold))))
   `(orderless-match-face-3 ((,class (:foreground ,success :weight bold))))
   `(orderless-match-face-4 ((,class (:foreground ,error :weight bold))))
   `(orderless-match-face-5 ((,class (:foreground ,keyword :weight bold))))

   ;; Marginalia
   `(marginalia-archive ((,class (:foreground ,info))))
   `(marginalia-char ((,class (:foreground ,constant))))
   `(marginalia-date ((,class (:foreground ,builtin))))
   `(marginalia-documentation ((,class (:foreground ,comment :slant italic))))
   `(marginalia-file-name ((,class (:foreground ,string))))
   `(marginalia-file-owner ((,class (:foreground ,warning))))
   `(marginalia-file-priv-dir ((,class (:foreground ,function))))
   `(marginalia-file-priv-exec ((,class (:foreground ,error))))
   `(marginalia-file-priv-link ((,class (:foreground ,keyword))))
   `(marginalia-file-priv-no ((,class (:foreground ,subtle))))
   `(marginalia-file-priv-other ((,class (:foreground ,info))))
   `(marginalia-file-priv-rare ((,class (:foreground ,warning))))
   `(marginalia-file-priv-read ((,class (:foreground ,success))))
   `(marginalia-file-priv-write ((,class (:foreground ,constant))))
   `(marginalia-function ((,class (:foreground ,function))))
   `(marginalia-key ((,class (:foreground ,keyword))))
   `(marginalia-lighter ((,class (:foreground ,comment))))
   `(marginalia-list ((,class (:foreground ,type))))
   `(marginalia-mode ((,class (:foreground ,builtin))))
   `(marginalia-modified ((,class (:foreground ,warning))))
   `(marginalia-null ((,class (:foreground ,subtle))))
   `(marginalia-number ((,class (:foreground ,constant))))
   `(marginalia-size ((,class (:foreground ,info))))
   `(marginalia-string ((,class (:foreground ,string))))
   `(marginalia-symbol ((,class (:foreground ,variable))))
   `(marginalia-true ((,class (:foreground ,success))))
   `(marginalia-type ((,class (:foreground ,type))))
   `(marginalia-value ((,class (:foreground ,constant))))
   `(marginalia-version ((,class (:foreground ,info))))

   ;; Org
   `(org-agenda-date ((,class (:foreground ,keyword))))
   `(org-agenda-date-today ((,class (:foreground ,keyword :underline t))))
   `(org-agenda-structure ((,class (:foreground ,builtin))))
   `(org-block ((,class (:background ,bg-darker :foreground ,fg))))
   `(org-block-begin-line ((,class (:background ,bg-bright :foreground ,subtle))))
   `(org-block-end-line ((,class (:background ,bg-bright :foreground ,subtle))))
   `(org-code ((,class (:foreground ,constant))))
   `(org-date ((,class (:foreground ,string :underline t))))
   `(org-document-title ((,class (:foreground ,keyword :height 1.5))))
   `(org-done ((,class (:foreground ,success))))
   `(org-headline-done ((,class (:foreground ,success))))
   `(org-level-1 ((,class (:foreground ,keyword :height 1.3))))
   `(org-level-2 ((,class (:foreground ,function :height 1.2))))
   `(org-level-3 ((,class (:foreground ,type))))
   `(org-level-4 ((,class (:foreground ,variable))))
   `(org-level-5 ((,class (:foreground ,constant))))
   `(org-link ((,class (:foreground ,builtin :underline t))))
   `(org-meta-line ((,class (:foreground ,comment))))
   `(org-priority ((,class (:foreground ,warning))))
   `(org-scheduled ((,class (:foreground ,info))))
   `(org-scheduled-today ((,class (:foreground ,info))))
   `(org-special-keyword ((,class (:foreground ,subtle))))
   `(org-table ((,class (:foreground ,fg))))
   `(org-tag ((,class (:foreground ,keyword))))
   `(org-todo ((,class (:foreground ,error))))
   `(org-upcoming-deadline ((,class (:foreground ,warning))))
   `(org-warning ((,class (:foreground ,error))))
   `(org-verbatim ((,class (:foreground ,constant :slant italic))))
   `(org-verse ((,class (:foreground ,string :slant italic))))
   `(org-checkbox ((,class (:background ,bg-darker :foreground ,fg :box (:line-width 1 :color ,fg)))))
   `(org-checkbox-statistics-todo ((,class (:foreground ,error))))
   `(org-checkbox-statistics-done ((,class (:foreground ,success))))

   ;; Diagnostics
   `(flymake-error ((,class (:underline (:style wave :color ,error) :foreground ,error))))
   `(flymake-warning ((,class (:underline (:style wave :color ,warning) :foreground ,warning))))
   `(flymake-note ((,class (:underline (:style wave :color ,info) :foreground ,info))))
   `(flymake-fringe-error ((,class (:foreground ,error))))
   `(flymake-fringe-warning ((,class (:foreground ,warning))))
   `(flymake-fringe-note ((,class (:foreground ,info))))
   `(flycheck-error ((,class (:underline (:style wave :color ,error) :foreground ,error))))
   `(flycheck-warning ((,class (:underline (:style wave :color ,warning) :foreground ,warning))))
   `(flycheck-info ((,class (:underline (:style wave :color ,info) :foreground ,info))))
   `(flycheck-fringe-error ((,class (:foreground ,error))))
   `(flycheck-fringe-warning ((,class (:foreground ,warning))))
   `(flycheck-fringe-info ((,class (:foreground ,info))))

   ;; Compilation
   `(compilation-error ((,class (:foreground ,error))))
   `(compilation-warning ((,class (:foreground ,warning))))
   `(compilation-info ((,class (:foreground ,info))))
   `(compilation-line-number ((,class (:foreground ,fg))))
   `(compilation-mode-line-fail ((,class (:foreground ,error))))
   `(compilation-mode-line-run ((,class (:foreground ,warning))))
   `(compilation-mode-line-exit ((,class (:foreground ,success))))

   ;; UI bits
   `(header-line ((,class (:background ,bg-bright :foreground ,fg :box nil))))
   `(tooltip ((,class (:background ,bg-darker :foreground ,fg))))
   `(button ((,class (:foreground ,keyword :underline t))))
   `(next-error ((,class (:background ,line-hl :foreground ,fg))))
   `(query-replace ((,class (:background ,line-hl :foreground ,fg))))

   ;; Company
   `(company-echo-common ((,class (:foreground ,error))))
   `(company-preview ((,class (:background ,line-hl :foreground ,fg))))
   `(company-preview-common ((,class (:background ,line-hl :foreground ,keyword))))
   `(company-preview-search ((,class (:background ,warning :foreground ,bg))))
   `(company-scrollbar-bg ((,class (:background ,bg-darker))))
   `(company-scrollbar-fg ((,class (:background ,line-hl))))
   `(company-template-field ((,class (:background ,warning :foreground ,bg))))
   `(company-tooltip ((,class (:background ,bg-darker :foreground ,fg))))
   `(company-tooltip-annotation ((,class (:foreground ,info))))
   `(company-tooltip-annotation-selection ((,class (:foreground ,info))))
   `(company-tooltip-common ((,class (:foreground ,keyword))))
   `(company-tooltip-common-selection ((,class (:foreground ,keyword))))
   `(company-tooltip-mouse ((,class (:background ,line-hl))))
   `(company-tooltip-search ((,class (:background ,warning :foreground ,bg))))
   `(company-tooltip-search-selection ((,class (:background ,warning :foreground ,bg))))
   `(company-tooltip-selection ((,class (:background ,line-hl :foreground ,fg))))

   ;; Corfu
   `(corfu-default ((,class (:background ,bg-darker :foreground ,fg))))
   `(corfu-current ((,class (:background ,line-hl :foreground ,fg))))
   `(corfu-border ((,class (:background ,border :foreground ,border))))
   `(corfu-annotation ((,class (:foreground ,info))))
   `(corfu-annotation-selection ((,class (:foreground ,info))))
   `(corfu-mouse ((,class (:background ,line-hl))))
   `(corfu-scrollbar-bg ((,class (:background ,bg-darker))))
   `(corfu-scrollbar-fg ((,class (:background ,line-hl))))

   ;; Consult
   `(consult-key ((,class (:foreground ,keyword))))
   `(consult-narrow-indicator ((,class (:foreground ,warning))))
   `(consult-preview-match ((,class (:background ,line-hl :foreground ,fg))))

   ;; Completion basics
   `(completion-common-part ((,class (:foreground ,keyword))))
   `(completion-first-difference ((,class (:foreground ,warning))))

   ;; Borders
   `(internal-border ((,class (:background ,border))))
   `(child-frame-border ((,class (:foreground ,border))))
   `(highlight-symbol-face ((,class (:background ,line-hl))))

   ;; Tree-sitter highlight (for users of tree-sitter-hl)
   `(tree-sitter-hl-face:type ((,class (:foreground ,type))))
   `(tree-sitter-hl-face:type.builtin ((,class (:foreground ,builtin))))
   `(tree-sitter-hl-face:interface ((,class (:foreground ,type))))
   `(tree-sitter-hl-face:struct ((,class (:foreground ,type))))
   `(tree-sitter-hl-face:enum ((,class (:foreground ,type))))
   `(tree-sitter-hl-face:constant ((,class (:foreground ,constant))))
   `(tree-sitter-hl-face:number ((,class (:foreground ,constant))))
   `(tree-sitter-hl-face:string ((,class (:foreground ,string))))
   `(tree-sitter-hl-face:escape ((,class (:foreground ,warning))))
   `(tree-sitter-hl-face:function ((,class (:foreground ,function :slant italic))))
   `(tree-sitter-hl-face:function.builtin ((,class (:foreground ,builtin))))
   `(tree-sitter-hl-face:method ((,class (:foreground ,function :slant italic))))
   `(tree-sitter-hl-face:property ((,class (:foreground ,variable))))
   `(tree-sitter-hl-face:variable ((,class (:foreground ,variable))))
   `(tree-sitter-hl-face:variable.builtin ((,class (:foreground ,builtin))))
   `(tree-sitter-hl-face:attribute ((,class (:foreground ,info))))
   `(tree-sitter-hl-face:label ((,class (:foreground ,type))))
   `(tree-sitter-hl-face:operator ((,class (:foreground ,keyword))))
   `(tree-sitter-hl-face:punctuation ((,class (:foreground ,subtle))))
   `(tree-sitter-hl-face:tag ((,class (:foreground ,keyword))))
   `(tree-sitter-hl-face:attribute ((,class (:foreground ,type))))

   ;; ERC (IRC Client)
   `(erc-default-face ((,class (:foreground ,fg))))
   `(erc-input-face ((,class (:foreground ,cursor :weight bold))))
   `(erc-prompt-face ((,class (:foreground ,cursor :weight bold))))
   `(erc-command-indicator-face ((,class (:foreground ,cursor :weight bold))))
   `(erc-current-nick-face ((,class (:foreground ,cursor :weight bold))))
   `(erc-my-nick-face ((,class (:foreground ,cursor :weight bold))))
   `(erc-my-nick-prefix-face ((,class (:foreground ,cursor :weight bold))))
   `(erc-nick-default-face ((,class (:foreground ,function))))
   `(erc-nick-msg-face ((,class (:foreground ,warning :weight bold))))
   `(erc-direct-msg-face ((,class (:foreground ,warning))))
   `(erc-pal-face ((,class (:foreground ,type :weight bold))))
   `(erc-fool-face ((,class (:foreground ,faded))))
   `(erc-dangerous-host-face ((,class (:foreground ,error :weight bold))))
   `(erc-timestamp-face ((,class (:foreground ,subtle))))
   `(erc-notice-face ((,class (:foreground ,error :weight bold))))
   `(erc-error-face ((,class (:foreground ,error :weight bold))))
   `(erc-action-face ((,class (:foreground ,variable :slant italic))))
   `(erc-button ((,class (:foreground ,builtin :underline t))))
   `(erc-keyword-face ((,class (:foreground ,keyword :weight bold))))
   `(erc-header-line ((,class (:background ,bg-bright :foreground ,fg))))
   `(erc-join-face ((,class (:foreground ,success :weight bold))))
   `(erc-part-face ((,class (:foreground ,warning :weight bold))))
   `(erc-quit-face ((,class (:foreground ,constant :weight bold))))
   `(erc-nick-change-face ((,class (:foreground ,info :weight bold))))
   `(erc-ctcp-face ((,class (:foreground ,constant))))
   `(erc-dcc-face ((,class (:foreground ,constant))))
   `(erc-underline-face ((,class (:underline t))))
   `(erc-mode-indicator-face ((,class (:foreground ,keyword :weight bold))))
   `(erc-away-face ((,class (:foreground ,faded :slant italic))))
   `(erc-topic-face ((,class (:foreground ,type :slant italic))))
   `(erc-op-face ((,class (:foreground ,error :weight bold))))
   `(erc-voice-face ((,class (:foreground ,warning))))
   `(erc-fill-wrap-merge-indicator-face ((,class (:foreground ,subtle))))
   `(erc-bold-face ((,class (:weight bold))))
   `(erc-inverse-face ((,class (:background ,fg :foreground ,bg))))
   `(erc-match-face ((,class (:background ,line-hl :foreground ,keyword :weight bold))))

   `(hel-normal-state-fake-cursor ((,class (:background ,type))))
   `(hel-insert-state-fake-cursor ((,class (:background ,type))))
   `(hel-extend-selection-cursor ((,class (:foreground ,cursor))))
   `(hel-search-highlight ((,class (:foreground ,cursor))))
   `(hel-mode-line-cursors-indicator ((,class (:foreground ,cursor))))

   ;; Scroll bars
   `(scroll-bar ((,class (:background ,bg-darker :foreground ,line-hl))))
   ))

(provide-theme 'sapporo-night)
;;; sapporo-night-theme.el ends here;;; sapporo-night-theme.el --- A bright dark theme, inspired by Tokyo Night Storm and Nord -*- lexical-binding: t; -*-

;; Copyright (C) 2025
;; Author: SoraTenshi
;; Version: 0.0.1
;; URL: https://github.com/yourname/sapporo-night-theme

;;; Commentary:
;; This file defines the Sapporo Night theme, a bright dark theme with purple-blue tones,
;; inspired by Tokyo Night Storm and Nord aesthetics.
;;; Code:

(deftheme sapporo-night
  "A bright dark theme with purple-blue tones, inspired by Tokyo Night Storm and Nord aesthetics.")

(let ((class '((class color) (min-colors 89)))
      (bg "#2a2947")
      (bg-bright "#51518B")
      (bg-darker "#202037")
      (fg "#a0b7eb")
      (fg-alt "#8bbaf3")
      (comment "#5FACF2")
      (keyword "#ab8bf7")
      (function "#9ab1fa")
      (string "#b0d4ff")
      (variable "#8bbaf3")
      (constant "#a9c7ff")
      (builtin "#94b5f0")
      (type "#8ea1ff")
      (line-hl "#33325d")
      (selection "#3b3b80")
      (cursor "#bb9af7")
      (error "#c678dd")
      (warning "#9dc8f8")
      (info "#87a3d4")
      (success "#56d8f4")
      (border "#404070")
      (subtle "#565f89")
      (faded "#4a5073"))

  (custom-theme-set-faces
   'sapporo-night

   ;; Base
   `(default ((,class (:background ,bg :foreground ,fg))))
   `(cursor ((,class (:background ,cursor))))
   `(region ((,class (:background ,selection :foreground ,fg))))
   `(secondary-selection ((,class (:background ,line-hl :foreground ,fg))))
   `(highlight ((,class (:background ,line-hl :foreground ,bg))))
   `(hl-line ((,class (:background nil :box (:line-width -1 :color ,line-hl)))))
   `(fringe ((,class (:background ,bg :foreground ,subtle))))
   `(vertical-border ((,class (:foreground ,border))))
   `(window-divider ((,class (:foreground ,border))))
   `(window-divider-first-pixel ((,class (:foreground ,border))))
   `(window-divider-last-pixel ((,class (:foreground ,border))))
   `(file-name-shadow ((,class (:foreground ,faded))))
   `(shadow ((,class (:foreground ,faded))))
   `(link ((,class (:foreground ,builtin :underline t))))
   `(link-visited ((,class (:foreground ,builtin :underline t))))

   ;; Font lock
   `(font-lock-builtin-face ((,class (:inherit nil :foreground ,builtin))))
   `(font-lock-comment-face ((,class (:inherit nil :foreground ,comment :slant italic))))
   `(font-lock-comment-delimiter-face ((,class (:inherit nil :foreground ,comment :slant italic))))
   `(font-lock-constant-face ((,class (:inherit nil :foreground ,constant))))
   `(font-lock-function-name-face ((,class (:inherit nil :foreground ,function :slant italic))))
   `(font-lock-keyword-face ((,class (:inherit nil :foreground ,keyword :slant italic))))
   `(font-lock-string-face ((,class (:inherit nil :foreground ,string))))
   `(font-lock-type-face ((,class (:inherit nil :foreground ,type))))
   `(font-lock-variable-name-face ((,class (:inherit nil :foreground ,variable))))
   `(font-lock-warning-face ((,class (:inherit nil :foreground ,warning))))
   `(font-lock-doc-face ((,class (:inherit nil :foreground ,comment :slant italic))))
   `(font-lock-preprocessor-face ((,class (:inherit nil :foreground ,builtin))))
   `(font-lock-negation-char-face ((,class (:inherit nil :foreground ,error))))
   `(font-lock-regexp-grouping-backslash ((,class (:inherit nil :foreground ,keyword))))
   `(font-lock-regexp-grouping-construct ((,class (:inherit nil :foreground ,constant))))
   `(font-lock-number-face ((,class (:inherit font-lock-constant-face))))
   `(font-lock-operator-face ((,class (:foreground ,keyword))))
   `(font-lock-delimiter-face ((,class (:foreground ,subtle))))
   `(font-lock-punctuation-face ((,class (:foreground ,subtle))))
   `(font-lock-escape-face ((,class (:foreground ,warning))))

   ;; Minibuffer / echo area
   `(minibuffer-prompt ((,class (:foreground ,keyword))))
   `(echo-area-message ((,class (:foreground ,fg))))

   ;; Mode line
   `(mode-line ((,class (:background ,line-hl :foreground ,fg :box nil))))
   `(mode-line-inactive ((,class (:background ,bg :foreground ,subtle :box nil))))
   `(mode-line-buffer-id ((,class (:foreground ,keyword))))

   ;; Line numbers
   `(line-number ((,class (:background ,bg :foreground ,subtle))))
   `(line-number-current-line ((,class (:inherit line-number :foreground ,fg :weight bold))))

   ;; Parens
   `(show-paren-match ((,class (:background ,line-hl :foreground ,fg :box (:line-width -1 :color ,keyword)))))
   `(show-paren-mismatch ((,class (:background ,error :foreground ,bg :weight bold))))

   ;; Search
   `(isearch ((,class (:background ,keyword :foreground ,bg :weight bold))))
   `(lazy-highlight ((,class (:background ,line-hl :foreground ,fg))))
   `(match ((,class (:background ,info :foreground ,bg :weight bold))))

   ;; Status faces
   `(error ((,class (:foreground ,error))))
   `(warning ((,class (:foreground ,warning))))
   `(success ((,class (:foreground ,success))))

   `(fill-column-indicator ((,class (:foreground ,faded :height 1.2))))

   ;; Whitespace
   `(whitespace-space ((,class (:foreground ,faded))))
   `(whitespace-tab ((,class (:foreground ,faded :background ,bg))))
   `(whitespace-newline ((,class (:foreground ,faded))))
   `(whitespace-trailing ((,class (:background ,error :foreground ,bg))))
   `(whitespace-line ((,class (:background nil :foreground nil))))
   `(whitespace-space-before-tab ((,class (:background ,bg :foreground ,warning :underline t))))
   `(whitespace-indentation ((,class (:background ,bg :foreground ,subtle))))
   `(whitespace-empty ((,class (:background ,bg-darker))))
   `(whitespace-space-after-tab ((,class (:background ,bg :foreground ,warning :underline t))))
   `(whitespace-missing-newline-at-eof ((,class (:background ,error :foreground ,bg))))
   `(whitespace-big-indent ((,class (:background ,bg :foreground ,warning))))
   `(whitespace-hspace ((,class (:foreground ,faded :background ,bg))))

   ;; Vertico
   `(vertico-current ((,class (:background ,line-hl :foreground ,fg))))
   `(vertico-group-title ((,class (:foreground ,keyword))))
   `(vertico-group-separator ((,class (:foreground ,border))))
   `(vertico-multiline ((,class (:foreground ,comment))))

   ;; Orderless
   `(orderless-match-face-0 ((,class (:foreground ,keyword :weight bold))))
   `(orderless-match-face-1 ((,class (:foreground ,warning :weight bold))))
   `(orderless-match-face-2 ((,class (:foreground ,info :weight bold))))
   `(orderless-match-face-3 ((,class (:foreground ,success :weight bold))))
   `(orderless-match-face-4 ((,class (:foreground ,error :weight bold))))
   `(orderless-match-face-5 ((,class (:foreground ,keyword :weight bold))))

   ;; Marginalia
   `(marginalia-archive ((,class (:foreground ,info))))
   `(marginalia-char ((,class (:foreground ,constant))))
   `(marginalia-date ((,class (:foreground ,builtin))))
   `(marginalia-documentation ((,class (:foreground ,comment :slant italic))))
   `(marginalia-file-name ((,class (:foreground ,string))))
   `(marginalia-file-owner ((,class (:foreground ,warning))))
   `(marginalia-file-priv-dir ((,class (:foreground ,function))))
   `(marginalia-file-priv-exec ((,class (:foreground ,error))))
   `(marginalia-file-priv-link ((,class (:foreground ,keyword))))
   `(marginalia-file-priv-no ((,class (:foreground ,subtle))))
   `(marginalia-file-priv-other ((,class (:foreground ,info))))
   `(marginalia-file-priv-rare ((,class (:foreground ,warning))))
   `(marginalia-file-priv-read ((,class (:foreground ,success))))
   `(marginalia-file-priv-write ((,class (:foreground ,constant))))
   `(marginalia-function ((,class (:foreground ,function))))
   `(marginalia-key ((,class (:foreground ,keyword))))
   `(marginalia-lighter ((,class (:foreground ,comment))))
   `(marginalia-list ((,class (:foreground ,type))))
   `(marginalia-mode ((,class (:foreground ,builtin))))
   `(marginalia-modified ((,class (:foreground ,warning))))
   `(marginalia-null ((,class (:foreground ,subtle))))
   `(marginalia-number ((,class (:foreground ,constant))))
   `(marginalia-size ((,class (:foreground ,info))))
   `(marginalia-string ((,class (:foreground ,string))))
   `(marginalia-symbol ((,class (:foreground ,variable))))
   `(marginalia-true ((,class (:foreground ,success))))
   `(marginalia-type ((,class (:foreground ,type))))
   `(marginalia-value ((,class (:foreground ,constant))))
   `(marginalia-version ((,class (:foreground ,info))))

   ;; Org
   `(org-agenda-date ((,class (:foreground ,keyword))))
   `(org-agenda-date-today ((,class (:foreground ,keyword :underline t))))
   `(org-agenda-structure ((,class (:foreground ,builtin))))
   `(org-block ((,class (:background ,bg-darker :foreground ,fg))))
   `(org-block-begin-line ((,class (:background ,bg-bright :foreground ,subtle))))
   `(org-block-end-line ((,class (:background ,bg-bright :foreground ,subtle))))
   `(org-code ((,class (:foreground ,constant))))
   `(org-date ((,class (:foreground ,string :underline t))))
   `(org-document-title ((,class (:foreground ,keyword :height 1.5))))
   `(org-done ((,class (:foreground ,success))))
   `(org-headline-done ((,class (:foreground ,success))))
   `(org-level-1 ((,class (:foreground ,keyword :height 1.3))))
   `(org-level-2 ((,class (:foreground ,function :height 1.2))))
   `(org-level-3 ((,class (:foreground ,type))))
   `(org-level-4 ((,class (:foreground ,variable))))
   `(org-level-5 ((,class (:foreground ,constant))))
   `(org-link ((,class (:foreground ,builtin :underline t))))
   `(org-meta-line ((,class (:foreground ,comment))))
   `(org-priority ((,class (:foreground ,warning))))
   `(org-scheduled ((,class (:foreground ,info))))
   `(org-scheduled-today ((,class (:foreground ,info))))
   `(org-special-keyword ((,class (:foreground ,subtle))))
   `(org-table ((,class (:foreground ,fg))))
   `(org-tag ((,class (:foreground ,keyword))))
   `(org-todo ((,class (:foreground ,error))))
   `(org-upcoming-deadline ((,class (:foreground ,warning))))
   `(org-warning ((,class (:foreground ,error))))
   `(org-verbatim ((,class (:foreground ,constant :slant italic))))
   `(org-verse ((,class (:foreground ,string :slant italic))))
   `(org-checkbox ((,class (:background ,bg-darker :foreground ,fg :box (:line-width 1 :color ,fg)))))
   `(org-checkbox-statistics-todo ((,class (:foreground ,error))))
   `(org-checkbox-statistics-done ((,class (:foreground ,success))))

   ;; Diagnostics
   `(flymake-error ((,class (:underline (:style wave :color ,error) :foreground ,error))))
   `(flymake-warning ((,class (:underline (:style wave :color ,warning) :foreground ,warning))))
   `(flymake-note ((,class (:underline (:style wave :color ,info) :foreground ,info))))
   `(flymake-fringe-error ((,class (:foreground ,error))))
   `(flymake-fringe-warning ((,class (:foreground ,warning))))
   `(flymake-fringe-note ((,class (:foreground ,info))))
   `(flycheck-error ((,class (:underline (:style wave :color ,error) :foreground ,error))))
   `(flycheck-warning ((,class (:underline (:style wave :color ,warning) :foreground ,warning))))
   `(flycheck-info ((,class (:underline (:style wave :color ,info) :foreground ,info))))
   `(flycheck-fringe-error ((,class (:foreground ,error))))
   `(flycheck-fringe-warning ((,class (:foreground ,warning))))
   `(flycheck-fringe-info ((,class (:foreground ,info))))

   ;; Compilation
   `(compilation-error ((,class (:foreground ,error))))
   `(compilation-warning ((,class (:foreground ,warning))))
   `(compilation-info ((,class (:foreground ,info))))
   `(compilation-line-number ((,class (:foreground ,fg))))
   `(compilation-mode-line-fail ((,class (:foreground ,error))))
   `(compilation-mode-line-run ((,class (:foreground ,warning))))
   `(compilation-mode-line-exit ((,class (:foreground ,success))))

   ;; UI bits
   `(header-line ((,class (:background ,bg-bright :foreground ,fg :box nil))))
   `(tooltip ((,class (:background ,bg-darker :foreground ,fg))))
   `(button ((,class (:foreground ,keyword :underline t))))
   `(next-error ((,class (:background ,line-hl :foreground ,fg))))
   `(query-replace ((,class (:background ,line-hl :foreground ,fg))))

   ;; Company
   `(company-echo-common ((,class (:foreground ,error))))
   `(company-preview ((,class (:background ,line-hl :foreground ,fg))))
   `(company-preview-common ((,class (:background ,line-hl :foreground ,keyword))))
   `(company-preview-search ((,class (:background ,warning :foreground ,bg))))
   `(company-scrollbar-bg ((,class (:background ,bg-darker))))
   `(company-scrollbar-fg ((,class (:background ,line-hl))))
   `(company-template-field ((,class (:background ,warning :foreground ,bg))))
   `(company-tooltip ((,class (:background ,bg-darker :foreground ,fg))))
   `(company-tooltip-annotation ((,class (:foreground ,info))))
   `(company-tooltip-annotation-selection ((,class (:foreground ,info))))
   `(company-tooltip-common ((,class (:foreground ,keyword))))
   `(company-tooltip-common-selection ((,class (:foreground ,keyword))))
   `(company-tooltip-mouse ((,class (:background ,line-hl))))
   `(company-tooltip-search ((,class (:background ,warning :foreground ,bg))))
   `(company-tooltip-search-selection ((,class (:background ,warning :foreground ,bg))))
   `(company-tooltip-selection ((,class (:background ,line-hl :foreground ,fg))))

   ;; Corfu
   `(corfu-default ((,class (:background ,bg-darker :foreground ,fg))))
   `(corfu-current ((,class (:background ,line-hl :foreground ,fg))))
   `(corfu-border ((,class (:background ,border :foreground ,border))))
   `(corfu-annotation ((,class (:foreground ,info))))
   `(corfu-annotation-selection ((,class (:foreground ,info))))
   `(corfu-mouse ((,class (:background ,line-hl))))
   `(corfu-scrollbar-bg ((,class (:background ,bg-darker))))
   `(corfu-scrollbar-fg ((,class (:background ,line-hl))))

   ;; Consult
   `(consult-key ((,class (:foreground ,keyword))))
   `(consult-narrow-indicator ((,class (:foreground ,warning))))
   `(consult-preview-match ((,class (:background ,line-hl :foreground ,fg))))

   ;; Completion basics
   `(completion-common-part ((,class (:foreground ,keyword))))
   `(completion-first-difference ((,class (:foreground ,warning))))

   ;; Borders
   `(internal-border ((,class (:background ,border))))
   `(child-frame-border ((,class (:foreground ,border))))
   `(highlight-symbol-face ((,class (:background ,line-hl))))

   ;; Tree-sitter highlight (for users of tree-sitter-hl)
   `(tree-sitter-hl-face:type ((,class (:foreground ,type))))
   `(tree-sitter-hl-face:type.builtin ((,class (:foreground ,builtin))))
   `(tree-sitter-hl-face:interface ((,class (:foreground ,type))))
   `(tree-sitter-hl-face:struct ((,class (:foreground ,type))))
   `(tree-sitter-hl-face:enum ((,class (:foreground ,type))))
   `(tree-sitter-hl-face:constant ((,class (:foreground ,constant))))
   `(tree-sitter-hl-face:number ((,class (:foreground ,constant))))
   `(tree-sitter-hl-face:string ((,class (:foreground ,string))))
   `(tree-sitter-hl-face:escape ((,class (:foreground ,warning))))
   `(tree-sitter-hl-face:function ((,class (:foreground ,function :slant italic))))
   `(tree-sitter-hl-face:function.builtin ((,class (:foreground ,builtin))))
   `(tree-sitter-hl-face:method ((,class (:foreground ,function :slant italic))))
   `(tree-sitter-hl-face:property ((,class (:foreground ,variable))))
   `(tree-sitter-hl-face:variable ((,class (:foreground ,variable))))
   `(tree-sitter-hl-face:variable.builtin ((,class (:foreground ,builtin))))
   `(tree-sitter-hl-face:attribute ((,class (:foreground ,info))))
   `(tree-sitter-hl-face:label ((,class (:foreground ,type))))
   `(tree-sitter-hl-face:operator ((,class (:foreground ,keyword))))
   `(tree-sitter-hl-face:punctuation ((,class (:foreground ,subtle))))
   `(tree-sitter-hl-face:tag ((,class (:foreground ,keyword))))
   `(tree-sitter-hl-face:attribute ((,class (:foreground ,type))))

   ;; ERC (IRC Client)
   `(erc-default-face ((,class (:foreground ,fg))))
   `(erc-input-face ((,class (:foreground ,cursor :weight bold))))
   `(erc-prompt-face ((,class (:foreground ,cursor :weight bold))))
   `(erc-command-indicator-face ((,class (:foreground ,cursor :weight bold))))
   `(erc-current-nick-face ((,class (:foreground ,cursor :weight bold))))
   `(erc-my-nick-face ((,class (:foreground ,cursor :weight bold))))
   `(erc-my-nick-prefix-face ((,class (:foreground ,cursor :weight bold))))
   `(erc-nick-default-face ((,class (:foreground ,function))))
   `(erc-nick-msg-face ((,class (:foreground ,warning :weight bold))))
   `(erc-direct-msg-face ((,class (:foreground ,warning))))
   `(erc-pal-face ((,class (:foreground ,type :weight bold))))
   `(erc-fool-face ((,class (:foreground ,faded))))
   `(erc-dangerous-host-face ((,class (:foreground ,error :weight bold))))
   `(erc-timestamp-face ((,class (:foreground ,subtle))))
   `(erc-notice-face ((,class (:foreground ,error :weight bold))))
   `(erc-error-face ((,class (:foreground ,error :weight bold))))
   `(erc-action-face ((,class (:foreground ,variable :slant italic))))
   `(erc-button ((,class (:foreground ,builtin :underline t))))
   `(erc-keyword-face ((,class (:foreground ,keyword :weight bold))))
   `(erc-header-line ((,class (:background ,bg-bright :foreground ,fg))))
   `(erc-join-face ((,class (:foreground ,success :weight bold))))
   `(erc-part-face ((,class (:foreground ,warning :weight bold))))
   `(erc-quit-face ((,class (:foreground ,constant :weight bold))))
   `(erc-nick-change-face ((,class (:foreground ,info :weight bold))))
   `(erc-ctcp-face ((,class (:foreground ,constant))))
   `(erc-dcc-face ((,class (:foreground ,constant))))
   `(erc-underline-face ((,class (:underline t))))
   `(erc-mode-indicator-face ((,class (:foreground ,keyword :weight bold))))
   `(erc-away-face ((,class (:foreground ,faded :slant italic))))
   `(erc-topic-face ((,class (:foreground ,type :slant italic))))
   `(erc-op-face ((,class (:foreground ,error :weight bold))))
   `(erc-voice-face ((,class (:foreground ,warning))))
   `(erc-fill-wrap-merge-indicator-face ((,class (:foreground ,subtle))))
   `(erc-bold-face ((,class (:weight bold))))
   `(erc-inverse-face ((,class (:background ,fg :foreground ,bg))))
   `(erc-match-face ((,class (:background ,line-hl :foreground ,keyword :weight bold))))

   ;; Magit
   `(magit-section-heading ((,class (:foreground ,keyword :weight bold))))
   `(magit-section-heading-selection ((,class (:foreground ,keyword :background ,selection))))
   `(magit-section-highlight ((,class (:background ,line-hl))))
   `(magit-diff-hunk-heading ((,class (:background ,bg-bright :foreground ,subtle))))
   `(magit-diff-hunk-heading-highlight ((,class (:background ,line-hl))))
   `(magit-diff-context ((,class (:foreground ,subtle))))
   `(magit-diff-context-highlight ((,class (:background ,line-hl :foreground ,subtle))))
   `(magit-diff-added ((,class (:background ,bg-darker :foreground ,success))))
   `(magit-diff-added-highlight ((,class (:background ,line-hl :foreground ,success))))
   `(magit-diff-removed ((,class (:background ,bg-darker :foreground ,error))))
   `(magit-diff-removed-highlight ((,class (:background ,line-hl :foreground ,error))))
   `(magit-diff-lines-boundary ((,class (:background ,line-hl))))
   `(magit-diffstat-added ((,class (:foreground ,success))))
   `(magit-diffstat-removed ((,class (:foreground ,error))))
   `(magit-hash ((,class (:foreground ,subtle :family "Monospace"))))
   `(magit-branch-local ((,class (:foreground ,function :weight bold))))
   `(magit-branch-remote ((,class (:foreground ,string :weight bold))))
   `(magit-branch-current ((,class (:foreground ,keyword :weight bold :underline t))))
   `(magit-tag ((,class (:foreground ,type))))
   `(magit-log-author ((,class (:foreground ,variable))))
   `(magit-log-date ((,class (:foreground ,subtle))))
   `(magit-reflog-head ((,class (:foreground ,keyword))))
   `(magit-reflog-other ((,class (:foreground ,subtle))))
   `(magit-reflog-reachable ((,class (:foreground ,variable))))
   `(magit-signature-bad ((,class (:foreground ,error :weight bold))))
   `(magit-signature-error ((,class (:foreground ,error :weight bold))))
   `(magit-signature-expired ((,class (:foreground ,warning))))
   `(magit-signature-good ((,class (:foreground ,success))))
   `(magit-signature-revoked ((,class (:foreground ,warning))))
   `(magit-signature-untrusted ((,class (:foreground ,warning))))
   `(magit-signature-unknown ((,class (:foreground ,warning))))
   `(magit-signature-valid ((,class (:foreground ,success))))
   `(magit-cherry-unmatched ((,class (:foreground ,subtle))))
   `(magit-cherry-equivalent ((,class (:foreground ,variable))))
   `(magit-bisect-bad ((,class (:foreground ,error))))
   `(magit-bisect-good ((,class (:foreground ,success))))
   `(magit-bisect-skip ((,class (:foreground ,warning))))
   `(magit-blame-date ((,class (:foreground ,subtle))))
   `(magit-blame-name ((,class (:foreground ,variable))))
   `(magit-process-ok ((,class (:foreground ,success))))
   `(magit-process-ng ((,class (:foreground ,error))))
   `(magit-header ((,class (:foreground ,fg))))
   `(magit-header-line ((,class (:inherit magit-section-heading))))

   ;; Hel mode
   `(hel-normal-state-fake-cursor ((,class (:background ,type))))
   `(hel-insert-state-fake-cursor ((,class (:background ,type))))
   `(hel-extend-selection-cursor ((,class (:foreground ,cursor))))
   `(hel-search-highlight ((,class (:foreground ,cursor))))
   `(hel-mode-line-cursors-indicator ((,class (:foreground ,cursor))))
   `(pulse-highlight-face ((,class (:foreground ,bg-darker :background ,comment))))
   `(pulse-highlight-start-face ((,class (:foreground ,bg-darker :background ,comment))))

   ;; Scroll bars
   `(scroll-bar ((,class (:background ,bg-darker :foreground ,line-hl))))

   ;; Dired (File Management)
   `(dired-header ((,class (:foreground ,keyword :weight bold))))
   `(dired-directory ((,class (:foreground ,function :weight bold))))
   `(dired-symlink ((,class (:foreground ,string :slant italic))))
   `(dired-mark ((,class (:foreground ,warning))))
   `(dired-flagged ((,class (:foreground ,error :weight bold))))
   `(dired-ignored ((,class (:foreground ,subtle))))
   `(dired-warning ((,class (:foreground ,warning :weight bold))))

   ;; Info / Man Pages
   `(info-title-1 ((,class (:foreground ,keyword :weight bold :height 1.4))))
   `(info-title-2 ((,class (:foreground ,function :weight bold :height 1.3))))
   `(info-title-3 ((,class (:foreground ,type :weight bold :height 1.2))))
   `(info-title-4 ((,class (:foreground ,constant :weight bold :height 1.1))))
   `(info-menu-header ((,class (:foreground ,keyword :weight bold))))
   `(info-menu-star ((,class (:foreground ,warning))))
   `(info-node ((,class (:foreground ,keyword))))
   `(info-xref ((,class (:foreground ,builtin :underline t))))
   `(info-string ((,class (:foreground ,string))))
   `(info-xref-visited ((,class (:inherit link-visited))))
   `(Man-overstrike ((,class (:foreground ,keyword :weight bold))))
   `(Man-underline ((,class (:foreground ,string :underline t))))

   ;; Xref (Navigation)
   `(xref-file ((,class (:foreground ,string))))
   `(xref-line-number ((,class (:foreground ,subtle))))
   `(xref-match ((,class (:foreground ,keyword :weight bold))))

   ;; Which-Key
   `(which-key-key-face ((,class (:foreground ,variable :weight bold))))
   `(which-key-separator-face ((,class (:foreground ,subtle))))
   `(which-key-group-description-face ((,class (:foreground ,function))))
   `(which-key-command-face ((,class (:foreground ,fg))))
   `(which-key-highlight-face ((,class (:background ,selection :foreground ,fg))))

   ;; Vundo (Undo Tree)
   `(vundo-last ((,class (:foreground ,keyword :weight bold))))
   `(vundo-next ((,class (:foreground ,fg))))
   `(vundo-save-undo ((,class (:foreground ,warning))))
   `(vundo-modified ((,class (:foreground ,error))))
   ))

(provide-theme 'sapporo-night)
;;; sapporo-night-theme.el ends here
